name: isharaapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ðŸ§© Ø£Ø³Ø§Ø³ÙŠØ©
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.4
  flutter_screenutil: ^5.9.3
  go_router: ^14.2.0
  flutter_svg: ^2.0.10+1


  # ðŸŒ™ Ø§Ù„Ø«ÙŠÙ…Ø§Øª ÙˆØ§Ù„Ù…Ø¸Ù‡Ø±
  sentry_flutter: ^8.2.0

  # ðŸª¶ Ø£Ø¯ÙˆØ§Øª Ø§Ù„Ø´Ø¨ÙƒØ© ÙˆØ§Ù„ØªØ­Ù„ÙŠÙ„
  http: ^1.2.2
  chucker_flutter: 1.8.5

  # ðŸ–¼ï¸ Ø§Ù„ØµÙˆØ± ÙˆØ§Ù„ØªØ­Ù…ÙŠÙ„
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.1

  # ðŸ§  Ø£Ø®Ø±Ù‰
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
